export const MutationKeys = {
    REGISTER_USER: "REGISTER_USER",
    INITI_USER_LOGIN: "INITI_USER_LOGIN",
    VERIFY_USER: "VERIFY_USER",
    CREATE_TENANT: "CREATE_TENANT",
    DELETE_TENANT: "DELETE_TENANT",
    ASSIGN_USER_TO_TENANT: "ASSIGN_USER_TO_TENANT",
};

export const QueryKeys = {
    USER_PROFILE: "USER_PROFILE",
    GET_UNVERIFIED_USERS: "GET_UNVERIFIED_USERS",
    GET_VERIFIED_USERS: "GET_VERIFIED_USERS",
    GET_TENANTS: "GET_TENANTS",
};
